service: triangle-database

custom:
  stage: ${opt:stage, self:provider.stage}
  region: sa-east-1
  MAIN_TABLE_NAME: ${self:custom.stage}-triangle

provider:
  name: aws
  runtime: nodejs14.x
  region: ${self:custom.region}

resources:
  Resources:
    MainTableTriangle:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.MAIN_TABLE_NAME}
  Outputs:
    MainTableTriangleArn:
      Value:
        Fn::GetAtt:
          - MainTableTriangle
          - Arn
      Export:
        Name: ${self:custom.stage}-MainTableTriangleArn
